### PR TITLE
set up hatch for dependency management

### PR DESCRIPTION
**Pull request by Artemis21**
This commit sets up a few things:
- [Hatch](https://hatch.pypa.io) which manages dependencies, virtual environments and stuff like that. The same kind of thing as Poetry or Pipenv, but better (IMHO).
- [Ruff](https://astral.sh/ruff), a linter which reimplements flake8 but faster, as far as I can tell. I have no preference between the two, this one just gets set up by default by Hatch, along with a long list of lints. We might want to disable some of those if they're unnecessarily annoying.
- [Black](https://black.readthedocs.io/en/stable/), a python code formatter.
- [Pre-commit](https://pre-commit.com), a tool that runs Black & Ruff for you before you commit to make sure everything passes linting.

I'm not attached to any of these things, so if people object or have alternatives, that's what this PR is for :)

### CODE REVIEW

**Comment by shner-elmo** [comment]
What are the advantages of using Hatch instead of Poetry?

**Comment by Artemis21** [comment]
> What are the advantages of using Hatch instead of Poetry?

I prefer Hatch because
- It has the ability to configure custom scripts (`hatch run lint`, etc.) built in. Poetry has [poethepoet](https://github.com/nat-n/poethepoet), but you have to install it separately.
- Hatch automatically creates environments, activates environments and installs dependencies as required when you run a command, so you can't forget to run `poetry install` or whatever. Of course this only works when you're running commands through Hatch.
- Using Poetry I've run in to confusing problems where environments or dependencies are somehow messed up and it's painful to fix. Probably this is thanks to my own mistakes, but I've not yet had the same problem with Hatch (could just be a matter of time).
- Hatch is maintained by the Python Packaging Authority. 

I am open to using Poetry if other people would prefer it though.

**Comment by shner-elmo** [comment]
Running custom scripts with a simple command is a neat feature, didn't know you could do it with Poetry.
I personally never had any issues handling virtual environments once I learned how Poetry works, but I'm excited to try this package manager maintained by PyPa!

**Review by shner-elmo — APPROVED** [review]
Once we know what the project is about, we should probably move the source a level deeper, i.e. `/src/pacakge_name/__init__.py`, so its not importable directly from the root directory, but instead you can only use it by pip installing it.

This will make our tests more reliable since they don't depend on the relative location of the source code, my two cents.

**Comment by Artemis21** [comment]
Good point @shner-elmo. I actually removed all of Hatch's pre-configured testing provisions because I thought it was a bit optimistic for a code jam, but maybe we should add them back.

**Comment by falkanson** [comment]
I also think that testing is a bit optimistic, last time we did not bother.

**Comment by shner-elmo** [comment]
Its my first code jam so I dont know if its expected or not to make tests for the project.

Personally I like to write unit tests for some critical parts of the project, which also helps me understand the code better.

How about we add a directory for tests in case anybody wants to write them, and at the end of the project we could decide if to inlcude it or not?

**Comment by falkanson** [comment]
I don't think it is required as long as the project works somewhat

**Comment by Artemis21** [comment]
I agree that it's not a requirement, but if people want to write them I think it can only improve the project. @shner-elmo it sounds like you have a good idea of what we should set up. Do you want to merge this and make a PR for that?

**Comment by shner-elmo** [comment]
@Artemis21 Sure, when I come home this evening I'll get it done

**Pull request merged**
